{
 "title": "Black box exporter",
 "description": "Prometheus blackbox exporter metrics.",
 "tags": [
  "Prometheus",
  "blackbox"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "database", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(probe_success,job)"
   },
   {
    "name": "targets",
    "label": "targets",
    "query": "label_values(up{job=~'$job'},url)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{url=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_http_version{url=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "HTTP Status code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code{job=~'$job',url=~'$targets'})",
     "legendFormat": "http status {{ value }}"
    }
   ]
  },
  {
   "title": "probe success / failure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " count_values('value',probe_success{job=~'$job',url=~'$targets'})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "probe success / failure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (value) (probe_http_status_code{job=~'$job',url=~'$targets'} - 0 == 200)",
     "legendFormat": "{{ url }}"
    },
    {
     "expr": "sum by (value) (probe_http_status_code{job=~'$job',url=~'$targets'} - 0 != 200)",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~'$job',url=~'$targets'}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "ICMP/HTTPS duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=~'PING-OS-VM',url=~'$targets'}",
     "legendFormat": "{{url}} {{phase}}"
    },
    {
     "expr": "probe_http_duration_seconds{job=~'$job',url=~'$targets'}",
     "legendFormat": "{{url}} {{phase}}"
    }
   ]
  },
  {
   "title": "Certificate & Connection Monitoring",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry-time()"
    },
    { "expr": "probe_http_status_code" },
    {
     "expr": "probe_http_duration_seconds{phase=\"resolve\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"tls\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"processing\"}"
    },
    {
     "expr": "probe_http_duration_seconds{phase=\"transfer\"}"
    }
   ]
  },
  {
   "title": "Global status",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "probe_success{url=~\"$targets\"} - 0 "
    },
    {
     "expr": "probe_http_ssl{url=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_http_status_code{url=~\"$targets\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{url=~\"$targets\"}-time()"
    }
   ]
  }
 ]
}